[tool.black]
line-length = 120
target_version = ['py310']

[tool.isort]
line_length = 120
multi_line_output = 3
lines_between_types = true
balanced_wrapping = true
include_trailing_comma = true
force_grid_wrap = false
use_parentheses = true
