apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-backend-deployment
spec:
  selector:
    matchLabels:
      app: chatbot-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: chatbot-backend
    spec:
      containers:
      - name: chatbot-backend
        image: GAR_LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE
        ports:
        - containerPort: 8000
        env:
        - name: FRONTEND_HOST
          valueFrom:
            configMapKeyRef:
              name: chatbot-backend-configmap
              key: feHost
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: chatbot-backend-configmap
              key: dbUrl
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.30.1
        command:
          - "/cloud_sql_proxy"
          # By default, the proxy will write all logs to stderr. In some
          # environments, anything printed to stderr is consider an error. To
          # disable this behavior and write all logs to stdout (except errors
          # which will still go to stderr), use:
          - "-log_debug_stdout"
          - "-instances=kindly-case:europe-north1:kindly-case=tcp:5432"
        securityContext:
          runAsNonRoot: true
      serviceAccountName: chatbot-backend-sql-sa